---
#- name: "apt-get upgrade"
#  apt:
#      upgrade: dist

- name: add additional repository 
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ repo_packages }}"

- name: update the system 
  raw: sudo apt-get update
  register: update_result
  changed_when: False
  until: update_result is success
  retries: 5
  ignore_errors: yes

- name: upgrade the system
  apt:
      name: "*"
      state: latest
      force_apt_get: True

- name: Install Packages
  apt:
      name: "{{ item }}"
      state: present
  loop: "{{ initial_packages }}"

- name: Disallow root SSH access
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin\s'
      line: 'PermitRootLogin no'
      state: present
  notify: Restart ssh

- name: Disallow empty passwords
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitEmptyPasswords\s'
      line: 'PermitEmptyPasswords no'
      state: present
  notify: Restart ssh

- name: Disallow password authentication
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication\s'
      line: 'PasswordAuthentication no'
      state: present
  notify: Restart ssh
 
