# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
	
numserverscentos = ENV['numserverscentos'] || "1"
numserverscentos = numserverscentos.to_i

numserversdebian = ENV['numserversdebian'] || "1"
numserversdebian = numserversdebian.to_i

serverscentos = Hash.new
(1..numserverscentos).each do |i|
    servernamecentos = "centos%02d" % i
    octet = i + 50
    serverscentos[servernamecentos] = {
      ip: "192.168.122.#{octet}"
    }
end

serversdebian = Hash.new
(1..numserversdebian).each do |i|
    servernamedebian = "debian%02d" % i
    octet = i + 100
    serversdebian[servernamedebian] = {
      ip: "192.168.122.#{octet}"
    }
end


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  (1..numserverscentos).each do |i|
      servernamecentos = "centos%02d" % i
      config.vm.define servernamecentos do |svr1|
        svr1.vm.provider "libvirt"
        svr1.vm.box = "centos/7"
        svr1.vm.synced_folder ".", "/vagrant", type: "rsync"
        svr1.vm.hostname = servernamecentos
        svr1.vm.network "private_network", ip: serverscentos [servernamecentos][:ip]
        svr1.vm.provision "shell",
          inline: "sudo yum update -y && sudo yum install -y python"
        svr1.vm.provision "ansible" do |ansible|
          ansible.playbook = "playbook_vagrant.yaml"
          ansible.verbose = true
          ansible.raw_arguments = ["--vault-id", "vault_pass"]
          ansible.extra_vars = {
            serverscentos: serverscentos
          }
        end
      end
  end

  (1..numserversdebian).each do |i|
      servernamedebian = "debian%02d" % i
      config.vm.define servernamedebian do |svr2|
        svr2.vm.provider "libvirt"
        svr2.vm.box = "debian/stretch64"
        svr2.vm.synced_folder ".", "/vagrant", type: "rsync"
        svr2.vm.hostname = servernamedebian
        svr2.vm.network "private_network", ip: serversdebian [servernamedebian][:ip]
        svr2.vm.provision "shell",
          inline: "sudo apt-get update -y && sudo apt install -y python"
        svr2.vm.provision "ansible" do |ansible|
          ansible.playbook = "playbook_vagrant.yaml"
          ansible.verbose = true
          ansible.raw_arguments = ["--vault-id", "vault_pass"]
          ansible.extra_vars = {
            serversdebian: serversdebian
          }
        end
      end
  end
end
